project:
  type: book
  output-dir: docs

lang: en

book:
  title: "Theory of Potential Field Methods in Geophysics"
  author: "Dr. Ralph-Uwe Börner"
  date: today
  chapters: 
    - index.qmd
    - intro.qmd
    - part: "Mathematical foundations"
      chapters: 
        - fields.qmd
#        - rubberband.qmd
#        - pde_example.qmd
    - part: "Newton potential"
      chapters: 
        - pointmass.qmd
#        - poisson_equation.qmd
        - mass_distribution.qmd
        - spherical_shells.qmd
        - PREM_.qmd
        - Sphere_Potential_and_Attraction.qmd
        - circular_disc.qmd
    - part: "Two-dimensional problems"
      chapters: 
        - line_of_mass.qmd
        - talwani.qmd
        - Talwani-Implementation.qmd
        - complex.qmd
        - hilbert.qmd
    - part: "Three-dimensional problems"
      chapters:
      - three-dimensional-problems.qmd
    - part: "Dipole potential"
      chapters:
      - electricaldipole.qmd
      - magneticdipole.qmd
    - part: "Spherical harmonics"
      chapters:
        - legendre-intro.qmd
        - legendre.qmd
    - part: "Boundary value problems"
    - summary.qmd
    - references.qmd

bibliography: references/literatur.bib
csl: https://www.zotero.org/styles/geophysical-journal-international

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    crossref:
      chapters: true
      eq-prefix: ""
    code-fold: true
    code-summary: "Show the code"
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            loader: {
              load: ['[tex]/physics']
            },
            tex: {
              packages: {'[+]': ['physics']}
            }
          };
          </script>
#  pdf: 
#    documentclass: scrreprt
#    papersize: a4

editor:
  render-on-save: true

